/*
  ==============================================================================
    This file was auto-generated by the Introjucer!
    It contains the basic framework code for a JUCE plugin editor.
  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class JuceGainAudioProcessorEditor : public AudioProcessorEditor,
                                     public SliderListener
{
public:
    JuceGainAudioProcessorEditor (JuceGainAudioProcessor&);
    ~JuceGainAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged(Slider* movedSlider);
    
private:
    const int WIDTH     = 240;
    const int HEIGHT    = 320;
    const int CENTER_X  = WIDTH/2;
    const int CENTER_Y  = HEIGHT/2;
    
    // Controls
    ScopedPointer<Slider> gainControl;
    ScopedPointer<Slider> panControl;

    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    JuceGainAudioProcessor& processor;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (JuceGainAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED